select * from Pais

ALTER TABLE CIDADE MODIFY NOM_CIDADE VARCHAR2(50);
ALTER TABLE PEDIDO ADD STATUS VARCHAR2(50);
commit;

INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
commit;
INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
commit;
INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
commit;
INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
commit;
INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
commit;
INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
commit;
INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
commit;
INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
commit;
INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
commit;
INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
commit;
INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
commit;
INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
commit;
INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
commit;
INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
commit;
INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
commit;
INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
commit;
INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
commit;
INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
commit;


